# Generated by Django 4.1 on 2022-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
